server:
  port: 8080

security:
  jwt:
    token:
      secret-key: oojnvijfdnvnwjw;dh,ld,hd'l,hld'mr[g;rltr[lg[rl[rl[lrergyetgejvwovnwionikwmkwcmjfenvjnvownvw

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring-mvc
    username: root
    password: root
  liquibase:
    enabled: false
    change-log: changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true