server:
  port: 8080

security:
  jwt:
    token:
      secret-key: x012345678

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring-mvc
    username: root
    password: root
  liquibase:
    enabled: true
    change-log: changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true